CREATE DATABASE SellingTicketDB;
GO

USE SellingTicketDB;
GO

CREATE TABLE [User] (
	[userId] INTEGER NOT NULL IDENTITY UNIQUE,
	[username] VARCHAR(25) NOT NULL UNIQUE,
	[email] NVARCHAR(50) NOT NULL UNIQUE,
	[phoneNumber] VARCHAR(12) UNIQUE,
	[password] VARCHAR(25) NOT NULL,
	[active] BIT NOT NULL DEFAULT 1,
	[ createdAt] DATE NOT NULL,
	[ updateAt] DATE NOT NULL,
	PRIMARY KEY([userId])
);
GO

CREATE TABLE [Role] (
	[roleId] INTEGER NOT NULL IDENTITY UNIQUE,
	[nameRole] VARCHAR(50) NOT NULL,
	[description] VARCHAR(255),
	PRIMARY KEY([roleId])
);
GO

CREATE TABLE [User_Role] (
	[userId] INTEGER NOT NULL UNIQUE,
	[roleId] INTEGER NOT NULL UNIQUE
);
GO

CREATE TABLE [Event] (
	[eventId] INTEGER NOT NULL IDENTITY UNIQUE,
	[nameEvent] VARCHAR(100) NOT NULL,
	[userId] INTEGER NOT NULL UNIQUE,
	[venueId] INTEGER NOT NULL UNIQUE,
	[description] NVARCHAR(255),
	[status] VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
	PRIMARY KEY([eventId])
);
GO

CREATE TABLE [Venue] (
	[venueId] INTEGER NOT NULL IDENTITY UNIQUE,
	[nameVenue] NVARCHAR(255) NOT NULL,
	[address] NVARCHAR(255) NOT NULL,
	PRIMARY KEY([venueId])
);
GO

CREATE TABLE [TicketTypes] (
	[ticketTypeId] INTEGER NOT NULL IDENTITY UNIQUE,
	[eventId] INTEGER NOT NULL UNIQUE,
	[ticketName] NVARCHAR(25) NOT NULL,
	[price] DECIMAL(16,2) NOT NULL,
	[ initialQuantity] INTEGER NOT NULL,
	[soldQuantit] INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY([ticketTypeId])
);
GO

CREATE TABLE [Ticket] (
	[ticketId] INTEGER NOT NULL IDENTITY UNIQUE,
	[ticketCode] VARCHAR(100) NOT NULL UNIQUE,
	[orderId] INTEGER NOT NULL UNIQUE,
	[ticketTypeId] INTEGER NOT NULL UNIQUE,
	[checkinStatus] BIT NOT NULL DEFAULT 0,
	[checkinTime] DATE NOT NULL,
	PRIMARY KEY([ticketId])
);
GO

CREATE TABLE [Order] (
	[orderId] INTEGER NOT NULL IDENTITY UNIQUE,
	[userId] INTEGER NOT NULL UNIQUE,
	[eventId] INTEGER NOT NULL UNIQUE,
	[promoCodeId] INTEGER NOT NULL UNIQUE,
	[totalAmount] DECIMAL(15,2) NOT NULL,
	[discountAmount] DECIMAL((15,2)) NOT NULL,
	[status] VARCHAR(20) NOT NULL DEFAULT 'pending',
	[createdAt ] DATE NOT NULL,
	PRIMARY KEY([orderId])
);
GO

CREATE TABLE [Promocode] (
	[promocodeId] INTEGER NOT NULL IDENTITY UNIQUE,
	[eventId] INTEGER NOT NULL UNIQUE,
	[code] VARCHAR(20) NOT NULL UNIQUE,
	[discountPercentage] INTEGER NOT NULL,
	[discountAmount] DECIMAL(15,2) NOT NULL,
	[maxUsage] INTEGER NOT NULL,
	[usedCount] INTEGER NOT NULL DEFAULT 0,
	[startDate] DATE NOT NULL,
	[endDate] DATE NOT NULL,
	[status] VARCHAR(20) NOT NULL DEFAULT 'active',
	PRIMARY KEY([promocodeId])
);
GO

CREATE TABLE [OrderItem] (
	[orderItemId] INTEGER NOT NULL IDENTITY UNIQUE,
	[orderId] INTEGER NOT NULL UNIQUE,
	[ticketTypeId] INTEGER NOT NULL UNIQUE,
	[quantity] INTEGER NOT NULL,
	[unitPrice] DECIMAL(15,2) NOT NULL,
	PRIMARY KEY([orderItemId])
);
GO

CREATE TABLE [Payment] (
	[paymentId] INTEGER NOT NULL IDENTITY UNIQUE,
	[orderId] INTEGER NOT NULL UNIQUE,
	[paymentMethod] VARCHAR(20) NOT NULL,
	[amount] DECIMAL(15,2) NOT NULL,
	[status] VARCHAR(10) NOT NULL,
	[ paymentTime] DATE NOT NULL,
	PRIMARY KEY([paymentId])
);
GO

CREATE TABLE [Checkin] (
	[checkinId] INTEGER NOT NULL IDENTITY UNIQUE,
	[ticketId] INTEGER NOT NULL UNIQUE,
	[result] VARCHAR(25) NOT NULL,
	[checkInBy] INTEGER NOT NULL UNIQUE,
	PRIMARY KEY([checkinId])
);
GO


ALTER TABLE [User]
ADD FOREIGN KEY([userId])
REFERENCES [User_Role]([userId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Role]
ADD FOREIGN KEY([roleId])
REFERENCES [User_Role]([roleId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [User]
ADD FOREIGN KEY([userId])
REFERENCES [Event]([userId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Event]
ADD FOREIGN KEY([venueId])
REFERENCES [Venue]([venueId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Event]
ADD FOREIGN KEY([eventId])
REFERENCES [TicketTypes]([eventId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Order]
ADD FOREIGN KEY([orderId])
REFERENCES [Ticket]([orderId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Ticket]
ADD FOREIGN KEY([ticketTypeId])
REFERENCES [TicketTypes]([ticketTypeId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Order]
ADD FOREIGN KEY([userId])
REFERENCES [User]([userId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Order]
ADD FOREIGN KEY([eventId])
REFERENCES [Event]([eventId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Promocode]
ADD FOREIGN KEY([eventId])
REFERENCES [Event]([eventId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Order]
ADD FOREIGN KEY([promoCodeId])
REFERENCES [Promocode]([promocodeId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [OrderItem]
ADD FOREIGN KEY([orderId])
REFERENCES [Order]([orderId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [OrderItem]
ADD FOREIGN KEY([ticketTypeId])
REFERENCES [TicketTypes]([ticketTypeId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Payment]
ADD FOREIGN KEY([orderId])
REFERENCES [Order]([orderId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Checkin]
ADD FOREIGN KEY([ticketId])
REFERENCES [Ticket]([ticketId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [Checkin]
ADD FOREIGN KEY([checkInBy])
REFERENCES [User]([userId])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO